### ISSUE TITLE
Calling PopOver inside a UITableViewCell class?

### ISSUE THREAD

**Issue by seenoevo** [hsylife/SwiftyPickerPopover#100]
Hi, sorry if this is not so obvious, and I didn't see any previous issues regarding this, but I have a `UITableViewController` class, and within one of my `UITableViewCell` class, I have a `UITextField`:

![untitled](https://user-images.githubusercontent.com/8109158/41512431-01f9aed0-723d-11e8-951c-01ce695bb28f.png)

I have an `IBAction` attached to the `UITextField` and I'm trying to present the PopOver, but I'm running into an issue where the `baseViewController` requires a `UIViewController` type.

![untitled](https://user-images.githubusercontent.com/8109158/41512462-6c09df8e-723d-11e8-9274-a74770814c43.png)

**What I've attempted to do:**

I referenced  the parent `UITableViewController` object when the cell is created, and passed it into `baseViewController`, but this resulted in the following:

![untitled](https://user-images.githubusercontent.com/8109158/41513161-8584baa6-724c-11e8-82a5-4cce9a824e44.png)

What's the best way to resolve this?

Thanks!

**Comment by hsylife** [comment]
You need to use delegate. I will add some code for demo. Give me some time. Thanks!

**Comment by hsylife** [comment]
I will release the demo code on the latest version (6.6.2). Please see it!

**Comment by seenoevo** [comment]
thanks I will inspect and get back to you soon!

**Comment by seenoevo** [comment]
just had a chance to test it and there is a bit of an issue:

![simulator screen shot - iphone 7 - 2018-06-22 at 00 51 59](https://user-images.githubusercontent.com/8109158/41764604-85140e1a-75b6-11e8-9033-9233a8457241.png)

**Firstly**, Is there a way to handle the case where the PopOver is positioned in the middle of the screen regardless of the position of the buttons, textfield, etc. that activates the PopOver?...It does not look very clean the way that it is.

**Secondly,** I'm not sure exactly what this does but including the code `.setPermittedArrowDirections(.down)` causes the following:

![simulator screen shot - iphone 7 - 2018-06-22 at 00 55 07](https://user-images.githubusercontent.com/8109158/41764756-f4678062-75b6-11e8-80c3-25c0e81e4791.png)

I've attached a sample project if you can further inspect. Thanks!

[TestProject.zip](https://github.com/hsylife/SwiftyPickerPopover/files/2126755/TestProject.zip)

**Comment by seenoevo** [comment]
@hsylife any updates?

**Comment by hsylife** [comment]
@seenoevo Hello. I'm super busy now! I want to take some time to inspect this issue. Thank you for sharing

**Comment by hsylife** [comment]
Hello, @seenoevo.
I've considered your question.
It seems what you are looking for is a modal picker, not a popover picker.

**Comment by hsylife** [comment]
Sorry for the delay for the the second question.
There is a way to lock the popover below the textfield.
`.setPermittedArrowDirections(.up)`.

But It may cause a layout issue when the textField is positioned near the bottom of your viewController.view.
