### ISSUE TITLE
DatePickerPopover dimmed background cannot be dismissed in v6.6.1

### ISSUE THREAD

**Issue by seenoevo** [hsylife/SwiftyPickerPopover#101]
I didn't check to see what was done in v6.6.1 but it broke some functionality.

I was using v6.6.0 and the `DatePickerPopover` was dismissed fine via the `Cancel` or `Done` button. But in v6.6.1, tapping either one of those dismisses the PopOver but the dimmed background is still present:

![simulator screen shot - iphone 7 - 2018-06-18 at 00 43 12](https://user-images.githubusercontent.com/8109158/41523960-a24610a6-7290-11e8-9d4f-fbb5a7f9d97c.png)

Attached is a simple project if you can inspect...thanks
[TestProject.zip](https://github.com/hsylife/SwiftyPickerPopover/files/2110357/TestProject.zip)

**Comment by hsylife** [comment]
I'm sorry to replay late!
I will fix it.

**Comment by hsylife** [comment]
I believe I've fixed the issue. Please confirm it.
Thank you, @seenoevo

**Comment by seenoevo** [comment]
confirmed working!

can you merge into master branch then?

**Comment by hsylife** [comment]
Yes. It will be. The branch is still working in progress. Because I have to add some demo code for the other issue.

**Comment by seenoevo** [comment]
great!...looking forward to testing it!
