### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by frankois944** [hsylife/SwiftyPickerPopover#108]
Hello,
this project is not compatible swift 4.2.

Thanks

**Comment by weakfl** [comment]
I've submitted a PR: #110

**Comment by myanalysis** [comment]
serious bummer, I also wanted to use this code.
looks great.

**Comment by hsylife** [comment]
@weakfl 
I appreciate for your PR. I will check it up from now

**Comment by hsylife** [comment]
I've merged it to the master. Thank you for your updates!
