### ISSUE TITLE
Not compatible with swift 5

### ISSUE THREAD

**Issue by nikGayko** [hsylife/SwiftyPickerPopover#117]
I'm using carthage and when I try to update framework with swift 5 build tools raise error:
`error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'SwiftyPickerPopoverDemo')`
building using swift 4.2.1 only show warning:
`warning: SwiftyPickerPopoverDemo isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it. (in target 'SwiftyPickerPopoverDemo')`

@hsylife Could it be fixed in short time?

**Comment by hsylife** [comment]
Hi nikGayko,
I've released the latest version 6.6.6, which supports for Swift 5.

Best,
Yuta
