### ISSUE TITLE
Calendar doesn't show anymore

### ISSUE THREAD

**Issue by daviddelmonte** [hsylife/SwiftyPickerPopover#126]
Hi, I'm now using Xcode 11.2.1, and have been using SPP for ages.  When I run on the simulator, all is well. When I run on a device, the calendar window opens, but there is no calendar shown. 

![IMG_0034](https://user-images.githubusercontent.com/114487/68486589-5f02b780-020f-11ea-8a29-d35c95e412cc.png)

**Comment by daviddelmonte** [comment]
A bit more info. The calendar shows on an iPhone. On the iPad, the Calendar is there as I can touch in the blank screen and a date shows in the label. I there a place I can mess with the fonts for the calendar dates.. Tha may need a tweak.

**Comment by lewis-smith** [comment]
I would guess this is related to https://github.com/hsylife/SwiftyPickerPopover/issues/115.
Was your device in dark mode?
