### ISSUE TITLE
Calls are not recognized 

### ISSUE THREAD

**Issue by Jevon718** [hsylife/SwiftyPickerPopover#14]
When trying to call StringPickerPopover the complier can't find it.  I have the pod installed and working.  No error on the import line, but none of the calls work.

**Comment by hsylife** [comment]
Hello, @Jevon718. Thanks for your report.
Unfortunately, I couldn't recreate this problem.

Does the issue navigator on your Xcode say something?

**Comment by aiyub007** [comment]
same issue..

**Comment by hsylife** [comment]
Hey guys,
I published another repository to grab a clue.
https://github.com/hsylife/TestSwiftyPickerPopover
I recognize that this projects on the repository are currently working.

**Comment by Jevon718** [comment]
Could it have anything to do with the version.  When I install its 1.1.0 but I notice you say to use 1.1.0.rc.2.  I type       pod ‘SwiftyPickerPopover’, ‘~> 1.1.0.rc.2’   in my pod file but it looks like it still installs 1.1.0.  Is my syntax right?

**Comment by Jevon718** [comment]
and no it doesn't say anything, sorry I forgot to say.

**Comment by Jevon718** [comment]
I dropped the whole SwiftyPickerPopover file into my project and it worked.  Didn't even have to convert it.  I will pod install if you get it working.  It's a great project BTW!

**Comment by hsylife** [comment]
Thanks @Jevon718,
SwiftyPickerPopover 1.1.0 which is written in Swift 2.3, has a bug when installing it via CocoaPods.
Please give a time to fix it.

Yuta

**Comment by Jevon718** [comment]
ok

**Comment by Jevon718** [comment]
@hsylife what do you think about getting the popover to appear just below the button or "tap" that activates it?  Is it suppose to already?

**Comment by hsylife** [comment]
I have fixed the issue as SwiftyPickerPopover 1.2.0 for Swift 2.3 has pushed to the branch "1.2.0".
Now, you can install it via CocoaPods 1.1.0.rc.2 by specifying "pod 'SwiftyPickerPopover '~> 1.2.0'" into your podfile.

Yuta

**Comment by hsylife** [comment]
@Jevon718 Do you mean that arrow direction of the popover should be permitted only .down? (or, it should be programable?)
