### ISSUE TITLE
Error in Carthage update

### ISSUE THREAD

**Issue by andre991** [hsylife/SwiftyPickerPopover#16]
<img width="572" alt="captura de tela 2016-10-18 as 21 44 30" src="https://cloud.githubusercontent.com/assets/8302454/19500456/260c95f2-957c-11e6-8f9d-b5273fbf5b77.png">
in carthage update the building show this error, and not build the framework.
*** Skipped building SwiftyPickerPopover due to the error:
Dependency "SwiftyPickerPopover" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/hsylife/SwiftyPickerPopover/issues/new

**Comment by hsylife** [comment]
@andre991, Thanks for your report.
I will fix it.

Yuta

**Comment by hsylife** [comment]
@andre991, it's done.

Yuta

**Comment by andre991** [comment]
@hsylife Thanks to fixed.
