### ISSUE TITLE
Popover shows in incorrect position if presented from UICollectionViewCell

### ISSUE THREAD

**Issue by kennyevo** [hsylife/SwiftyPickerPopover#19]
I have a UICollectionView, and I wanted to show this popover when a user selects a cell, but if I set the cell as the originView, it doesn't show in the correct place.

**Comment by hsylife** [comment]
@kennyevo, thanks for your report. I will check it.

**Comment by kennyevo** [comment]
I have changed the line:
navigationController.popoverPresentationController?.sourceView = baseViewController.view

to

navigationController.popoverPresentationController?.sourceView = originView.superview!

And it looks good. Maybe it should be originView.superview ?? baseViewController.view

**Comment by hsylife** [comment]
@kennyevo, thanks for your hint. I will improve the code.

**Comment by hsylife** [comment]
It's done for Swift 3. I will adjust the version for Swift 2.3 in a few days.

**Comment by hsylife** [comment]
The new version for Swift 2.3 is available as SwiftyPickerPopover 1.3.0.

**Comment by TJSartain** [comment]
Is this still being used and maintained. I like how simple it is to get up and running. I wonder if anyone has made it so that outside taps are ignored - in other words, a modal popup.

**Comment by hsylife** [comment]
@TJSartain What is the diff between the Sample and yours?

**Comment by TJSartain** [comment]
I was using it as a popup (not from a table cell) and when I tapped outside of it, it closed. I wanted it to be modal where I would only be able to dismiss it using a cancel or done button.

**Comment by hsylife** [comment]
@TJSartain Thank you for your proposal. You can folk it and manipulate it as the following code:

```
extension AbstractPickerPopoverViewController: UIPopoverPresentationControllerDelegate {
    /// Popover appears on iPhone
    open func adaptivePresentationStyle(for controller: UIPresentationController, traitCollection: UITraitCollection) -> UIModalPresentationStyle {
        return .fullScreen // Not .none
    }
}
```

I consider the identity of this micro library, which has the suffix "Popover"...
