### ISSUE TITLE
Direction of popover

### ISSUE THREAD

**Issue by Touchcore** [hsylife/SwiftyPickerPopover#23]
How can I specify if I want the popover to appear on the left, right, up, or down side of the button?

**Comment by hsylife** [comment]
There is no argument to specify the arrow direction. Currently, you need to edit the code directly as the following in AbstractPopover.swift.

// direction of arrow
navigationController.popoverPresentationController?.permittedArrowDirections = .any

**Comment by Touchcore** [comment]
Thanks a lot. I found it.

**Comment by hsylife** [comment]
Thanks for giving a hint. I'd like to add an argument to SwiftyPickerPopover to make it easy.

**Comment by hsylife** [comment]
Finally I has released the new version 2.5.0 which has permittedArrowDirections argument.
