### ISSUE TITLE
Minute Interval

### ISSUE THREAD

**Issue by mike29892** [hsylife/SwiftyPickerPopover#24]
Is there no way to change the minute interval of the UIDatePicker?

**Comment by hsylife** [comment]
You can edit the code in DatePickerPopoverViewController.swift directly as the following.

    override func viewDidLoad() {
        super.viewDidLoad()
        picker.date = selectedDate
        picker.datePickerMode = dateMode
        //edited
       picker.minuteInterval = 10
    }

Plus, I'd like to add an argument to DatePickerPopoverViewController to make it easy.

**Comment by mike29892** [comment]
Thank you for the response. I thought that was the only way. It'd be nice to be able to do this with out editing the library, causing people to make a fork.

**Comment by hsylife** [comment]
Finally, I has released the new version 2.5.0 which has minuteIntervals argument.

**Comment by mike29892** [comment]
Thank you. This does not work with a pod install.

**Comment by mike29892** [comment]
It was an error with a bad pod update, all is good.
