### ISSUE TITLE
How to set Min/Max date range in DatePickerPopover

### ISSUE THREAD

**Issue by asadali737** [hsylife/SwiftyPickerPopover#25]
I couldn't found a way to set min/max date when showing date pickers. There's only one parameter available to set selected date.

**Comment by hsylife** [comment]
You have to edit the code as you can specify the min/max date in the latest version.

We should add `minimumDate` and 'maximumDate` arguments into .appearFrom() like here.

```
public class DatePickerPopover: AbstractPopover {

  public class func appearFrom(originView: UIView, baseView: UIView? = nil, baseViewController: UIViewController, title: String?, permittedArrowDirections:UIPopoverArrowDirection = .any, dateMode:UIDatePickerMode, initialDate:Date,
 minimumDate:Date? = nil,  maximumDate :Date? =nil,
 minuteInterval:Int = 0 ,doneAction: ((Date)->Void)?, cancelAction: (()->Void)?, clearAction: (()->Void)? = nil)

```

I'd like to add these parameters to the future version as soon as possible.

**Comment by hsylife** [comment]
I introduced minimumDate and maximumDate arguments to DatePickerPopover.appearFrom() in SwiftyPickerPopover 2.6.0 branch.
