### ISSUE TITLE
How to hide PickerPopover programmatically. 

### ISSUE THREAD

**Issue by asadali737** [hsylife/SwiftyPickerPopover#26]
I need to hide visible PickerPopover programmatically. Is there a way to do so?

Like if a PickerPopover is visible on screen, how could I hide it without any user interaction with screen.

**Comment by hsylife** [comment]
You can hide PickerPopover programmatically by calling `baseViewController.dismiss(animated:, completion:)` after `PickerPopover.appearFrom()` like this,
```
StringPickerPopover.appearFrom(originView: sender, baseViewController: self, title: "StringPicker", choices: ["value 1","value 2","value 3"], displayStringFor: displayStringFor, initialRow:0, doneAction: { selectedRow, selectedString in print("done row \(selectedRow) \(selectedString)")} , cancelAction: { print("cancel")})

self.dismiss(animated: false, completion: nil)
```
