### ISSUE TITLE
Dismiss timer needed

### ISSUE THREAD

**Issue by asadali737** [hsylife/SwiftyPickerPopover#27]
It would be great if there's a timer functionality available to automatically dismiss visible PickerPopover after given time if there's no user interaction.

**Comment by hsylife** [comment]
It looks like a good idea. I'd like to add a function to hide the popover itself automatically by specifying the seconds as an argument in the future version.

**Comment by hsylife** [comment]
I introduced some new arguments into pickerPopovers in SwiftyPickerPopover 2.6.0 branch.
They are to specify the time to hide the popover and the action to be performed after hidden.
