### ISSUE TITLE
show wrong cell with tableView.

### ISSUE THREAD

**Issue by mhtranbn** [hsylife/SwiftyPickerPopover#28]
hi @hsylife show wrong cell (layout)with tableView .Many thank for support.

**Comment by hsylife** [comment]
Hello @mhtranbn,
Thanks for your opening this issue.
Do you mean the arrow should be closer to the center of the cell?

![simulator screen shot 2017 03 11 22 10 14](https://cloud.githubusercontent.com/assets/11023238/23823550/2a2c392e-06a8-11e7-9cb6-fd33ba190987.png)

**Comment by mhtranbn** [comment]
yup, and when you set it is button this not show on button on cell (cell.button). Many thank for supports.

**Comment by hsylife** [comment]
@mhtranbn, can you show me your code and screenshot?

**Comment by mhtranbn** [comment]
if let dequeCell = self.tableView.dequeueReusableCell(withIdentifier: cellID[0]) as? AddBankAccountCurrencyCell {
       StringPickerPopover.appearFrom(originView: dequeCell.button, baseViewController: self, title: "StringPicker", choices: ["value 1","value 2","value 3"], displayStringFor: displayStringFor, initialRow:0, doneAction: { selectedRow, selectedString in print("done row \(selectedRow) \(selectedString)")} , cancelAction: { print("cancel")})
}

**Comment by hsylife** [comment]
@mhtranbn,
I reproduced the situation as possible as I can as the following screenshot.
Could you tell me what is the problem in detail?
![simulator screen shot 2017 03 12 22 36 32](https://cloud.githubusercontent.com/assets/11023238/23832239/654a9358-0774-11e7-9984-e923ae67dc95.png)

**Comment by mhtranbn** [comment]
My popup didnt same, cancel with done out size popup, and not show at button. Many thank for supports.

**Comment by hsylife** [comment]
@mhtranbn,
I understand that Your popup is not same. 
But I need more explanations to understand what you say at the latter half.

**Comment by dipeshparashar** [comment]
I have similar issue. If i have 6 textfields in a view. and only 1 of it has SwiftyPickerPopover. The SwiftyPicker opens up on all. I can share the project if you need it.

**Comment by hsylife** [comment]
@dipeshparashar, thanks for your reporting. 

I understood your situation that will be fixed by the next version of SwiftyPickerPopover.
The version has been under development.

**Comment by hsylife** [comment]
Hello guys,
I've pushed the rewritten version into the branch of '3.0.0' and made a braking change on it which is more swifty and less bugs.
You can easily understand the new syntax by looking at the Demo target and SampleViewController.swift. 

Please try it before the official release.

The new documents about how to use it are to be upcoming soon.

**Comment by hsylife** [comment]
https://github.com/hsylife/SwiftyPickerPopover/tree/3.0.0

**Comment by hsylife** [comment]
Hello guys,
I have released the 3.0.0 as a public release.
