### ISSUE TITLE
Command Line Tools for Xcode8.3 で carthage update に失敗する

### ISSUE THREAD

**Issue by taketomato** [hsylife/SwiftyPickerPopover#29]
お世話になっています。
Command Line Tools for Xcode8.3 で carthage update でのビルドに失敗します。
clone してきてのビルドはできます。

対策願えないでしょうか。お願いいたします。

**Comment by hsylife** [comment]
ありがとうございます。後ほど確認いたしますね。

**Comment by hsylife** [comment]
すみません、作業が抜けておりました。今はcarthage updateできるはずです。

**Comment by hsylife** [comment]
@taketomato その後、できましたでしょうか？

**Comment by taketomato** [comment]
@hsylife 
すみません、返信が遅くなりました。
ビルドすることができました。対応ありがとうございました！
