### ISSUE TITLE
Minute intervals issue

### ISSUE THREAD

**Issue by jarchille** [hsylife/SwiftyPickerPopover#30]
Hi, I'm trying to set my timepicker to display minutes in 5 minute increments (1:30 --> 1:35 --> 1:40 etc). However, when I try to use the provided example code (see below), the editor throws an error indicating that the DatePickerPopover class cannot take arguments the way its shown in the example code. 

       DatePickerPopover(title: "DatePicker .time 5minInt.")
                  .setDateMode(.time)
                  .setMinuteInterval(5)  
                  .setPermittedArrowDirections(.down)
                  .setDoneAction({ popover, selectedDate in print("selectedDate \(selectedDate)")} )
                  .setCancelAction({ popover in print("cancel")})
                 .appear(originView: sender, baseViewController: self)
      )

I looked through the relevant code and saw that there is a "DatePickerPopover.appearFrom..." call I can use. The problem is, that call doesn't appear to include an option to set minute increments.

Any ideas?

**Comment by hsylife** [comment]
Hello @jarchille 
Thanks for your question.
First, could you give me your active version of SwiftyPickerPopover?
The way to specify the minute interval, which was shown in the example code, is available only on the 3.0.0 or later.

**Comment by jarchille** [comment]
Hi, well then, that explains that! I was running version 2.4.1. 
I've downloaded the most recent release and, problem solved 👍 

Many thanks

**Comment by hsylife** [comment]
Hello @jarchille
I'm glad to hear that.
See you!
