### ISSUE TITLE
Why not include customizable button titles and arrow colors?

### ISSUE THREAD

**Issue by perroyverde** [hsylife/SwiftyPickerPopover#34]
The navigationbar color of the pickers change with my app navbar color but the arrow of the popoverPresentationController doesn't. 

Also, the Cancel and Done buttons text are not customizable.

I wonder if it could be implemented.

Thx

**Comment by hsylife** [comment]
Thank you for your suggestions, @perroyverde 

1. Add a function to set arrow color.
2. Change Cancel and Done buttons to Custom buttons.

It's basically a good thing to increase the freedom to be customized.
Please give me some time to consider them.

**Comment by hsylife** [comment]
Hello, @perroyverde 
I have released SwiftyPickerPopover 4.0.0 for your requests.
Please check it up!

**Comment by perroyverde** [comment]
Hi @hsylife,

I've just updated and it works great! Much more flexible now!
👍  Awesome and thank you very much for the effort!

**Comment by ghousenaren** [comment]
could you kindly share the code, where we need to change cancel and done button color, thank in adv

**Comment by hsylife** [comment]
Hello, @ghousenaren 
Would you like to change cancel and done button color?
We need to change Popover's tint color.
I should add a setter to AbstractPopover as soon as possible.

**Comment by hsylife** [comment]
@ghousenaren 
I've released the new version.
Now, you can specify the color of each button like this.

`.setCancelButton(color: UIColor.red, action: {_, _, _ in print("cancel") })
`
The **color:** parameters are available for **setDoneButton, setCancelButton, and setClearButton.**

And this is **omissible**. If you don't specify it, then SwiftyPickerPopover sets tintColor that inherits view.tintColor of appear()'s baseViewController, into each button. In many case, it works well.

---
The Swift4 version will follow the update soon.

**Comment by ghousenaren** [comment]
Thanks @hsylife, it worked like a charm..

**Comment by hsylife** [comment]
I have released the new Swift 4 version, 4.2.0.
https://github.com/hsylife/SwiftyPickerPopover/tree/swift4
