### ISSUE TITLE
Doesn't pop with the correct BaseView : When multiple pickers are in a view.

### ISSUE THREAD

**Issue by dipeshparashar** [hsylife/SwiftyPickerPopover#38]
I had reported this last month. The issue still persists even after updating and changing syntax to the latest version. If i have 10 textfields in a view and only 1-2 of them are SwiftyPicker, they pop randomly on other textfields too when they shouldn't. Moreover they never pop exactly with the baseView.

**Comment by hsylife** [comment]
Thank you for your report. Could you share your code?

**Comment by dipeshparashar** [comment]
Hi, sorry for delayed response. Issue still exists.
Here is the [project](https://we.tl/yMDeCdcRd8) 
Try all the fields & buttons marked with red.

**Comment by hsylife** [comment]
Hello @dipeshparashar 
Thank you for your sharing.
I will reply to you by the end of this weekend.
Best,

**Comment by hsylife** [comment]
Dear @dipeshparashar ,
You need to set baseView: to appear() on SwiftyPickerPopover 4.0.1 like this.
`.appear(originView: originView, baseView: originView.superview, baseViewController: self)`

If you update SwiftyPickerPopover to the latest version, you will fix it without rewriting code.
I recommend that you do `pod update` on terminal and build it again.

**Comment by dipeshparashar** [comment]
Thanks @hsylife . It really helped!

**Comment by hsylife** [comment]
Hello @dipeshparashar,
I'd like to know whether we've solved the issue or not.
May I close it?

**Comment by dipeshparashar** [comment]
Hi @hsylife , 
Yes, the issue is resolved please close it.

**Comment by dipeshparashar** [comment]
@hsylife 
Can we set the date formats. For eg. Day/Month/Year (rather than the default which is Month/Day/Year)

**Comment by hsylife** [comment]
@dipeshparashar 
Since it is a different topic, please make another issue.
The date format follows the Region setting by the user.
Are you asking for a way to force it to change it to another format?
