### ISSUE TITLE
don't run library for ios 9.3

### ISSUE THREAD

**Issue by kenias** [hsylife/SwiftyPickerPopover#39]
error.

2017-05-17 11:42:48.048 smartbeekeeping[244:17604] *** Assertion failure in -[UIPickerTableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UITableView.m:10594
2017-05-17 11:42:48.137 smartbeekeeping[244:17604] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView dataSource is not set'
*** First throw call stack:
(0x2412391b 0x238bee17 0x241237f1 0x24907529 0x289e5415 0x289e55a5 0x289d4b51 0x289e9d1b 0x2878923b 0x28d93ac5 0x286ad541 0x28d93a67 0x2869aa73 0x26732bcd 0x2672e375 0x286b0fe7 0x2875caed 0x2875a783 0x287735ff 0x2877335b 0x287730a7 0x286d9685 0x286d79c5 0x287660b9 0x287659ef 0x2875c2bd 0x2875b55f 0x2875b1b5 0x2875b12b 0x2869aa73 0x26732bcd 0x2672e375 0x2672e209 0x2672d6d1 0x2672d3a5 0x28691b79 0x240e56c9 0x240e39cd 0x240e3dff 0x24033229 0x24033015 0x25623ac9 0x28707189 0x17abd8 0x23cdb873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hsylife** [comment]
@kenias Thank you for your issue report. Unfortunately, I couldn't reproduce this issue on iOS 9, 9.3, and 10.3 simulator. I need more information, especially about your dataSource code. The error message seems to indicate that an inconsistency has occurred between the table row and the data in the dataSource.

**Comment by hsylife** [comment]
@kenias Sorry. I have confirmed that DatePicker has a bug on iOS 9.0 and iOS 9.3. This seems that you mentioned. I will fix it.

**Comment by hsylife** [comment]
@kenias Finally, I've released Ver 4.0.1. I appreciate for your collaboration!

**Comment by kenias** [comment]
Thank you. I will test.

**Comment by kenias** [comment]
i have test.
this library perpect running for ios 9.3.5;
Thank You. Good Man.

**Comment by hsylife** [comment]
Thank you for taking the time for test.
