### ISSUE TITLE
Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by ibolat38** [hsylife/SwiftyPickerPopover#41]
I get [this](https://i.hizliresim.com/qWYGoV.png) error when i build project.

**Comment by hsylife** [comment]
Hello, @ibolat38 
I couldn't reproduce this issue.
1) Did you confirm that the demo project works correctly? 
2) Will not it change even if you do Clean & Run? I doubt that the indexing is not working properly.

**Comment by ibolat38** [comment]
Hello dear @hsylife firstly sorry my bad english. I tried to run demo project its work perfectly but i set this library my own project using cocoa this time it gives me error in the first comment.

**Comment by hsylife** [comment]
@ibolat38, Thank you for your reply.
How about the 2nd question? Did you try doing clean & run?

**Comment by ibolat38** [comment]
@hsylife , sure i did clean & run. Actually for example when DatePickerPopover, StringPickerPopover or CountdownPickerPopover get parameter [like this](https://i.hizliresim.com/lW9jdQ.png) it gives that error.

**Comment by hsylife** [comment]
@ibolat38, if you click the function name such as "DatePickerPopover" with pressing command key, what will be displayed?

How do you install SwiftyPickerPopover into your project? Via cocoaPods? Carthage? Manually?

When I face the indexing problem, I attempt to clear the cache of Xcode. 
 Xcode->Preference->Locations-> Derived Data
Click the arrow to the folder.
Remove the folder, "DerivedData".
Reboot Xcode and open the project again.
