### ISSUE TITLE
Picker appears always above left

### ISSUE THREAD

**Issue by eironeia** [hsylife/SwiftyPickerPopover#48]
Thank you very much for the picker it's really beautiful, by the wat I can not get the way to place the "arrow" of the picker below or above the sender (button).

I have the following code but the picker appears above to the left always.

`     @IBAction func pickDateButtonPressed(_ sender: UIButton) {
    DatePickerPopover(title: "DatePicker")
            .appear(originView: sender, baseViewController: self)
    }`
            
![img_6092](https://user-images.githubusercontent.com/12100457/28143091-28efe7dc-6764-11e7-8cb3-49fb7010837e.PNG)

Probably is an stupid thing that I am missing, but it would be great if you can guide me!

Thank you very much!

**Comment by eironeia** [comment]
Hey there! Checking the resolved issues I realized that someone has had the same issue.

The solution it's the same that he has purpouse here (https://github.com/hsylife/SwiftyPickerPopover/issues/19)

"I have changed the line in AbstractPopover:
navigationController.popoverPresentationController?.sourceView = baseViewController.view

to

navigationController.popoverPresentationController?.sourceView = originView.superview!

And it looks good. Maybe it should be originView.superview ?? baseViewController.view"


Maybe is a bug on Swift 3 version, thank you again!

**Comment by hsylife** [comment]
Hello @eironeia, thank you for your posts.

I'm not sure about the difference between the demo code (ex. DatePicker .time 5min's arrow appears the center of the picker below) and your case.

Could you more detail info about the "sender" to improve our code.

`@IBAction func pickDateButtonPressed(_ sender: UIButton) { DatePickerPopover(title: "DatePicker") .appear(originView: sender, baseViewController: self) }`

In this case, what is the sender.frame?
"sender"(UIButton) was addSubviewed to self.view?

**Comment by eironeia** [comment]
Hello @hsylife, the sender is a button created on mainstoryboard. I have printed the frame as you request me of the sender button and I received that: (70.0, 0.0, 26.0, 32.0).

Okay, I think I have found my mistake. I have the button embed in a Stack View. So I am pretty sure I am getting the coordinates of the stack view but is applying to the self.view instead of stack view.

**Comment by eironeia** [comment]
I guess you can proceed to close the issue. Thank you for your fast reply.

**Comment by hsylife** [comment]
@eironeia Thank you for your reply.
I guess you can solve the issue as the following code.
`.appear(originView: sender, baseView: stackView ,baseViewController: self) }`

If originView.superView != baseViewController.view, then we need to set baseView: to specify the position of the arrow.

**Comment by eironeia** [comment]
Thank you so much! :)
