### ISSUE TITLE
Popovers crashes on iOS 11 

### ISSUE THREAD

**Issue by tfsjohan** [hsylife/SwiftyPickerPopover#59]
cancelButton is nil

https://github.com/hsylife/SwiftyPickerPopover/blob/master/SwiftyPickerPopover/DatePickerPopoverViewController.swift#L16

**Comment by hsylife** [comment]
@tfsjohan 
Thank you for the information. 
I will fix it.

**Comment by tfsjohan** [comment]
I just added a ? to the call, but then I don't get a cancel button at all. If it helps I set my own localized title with:

`.setCancelButton(title: NSLocalizedString("Cancel", comment: ""), action: nil)`

**Comment by hsylife** [comment]
@tfsjohan 
As you wrote, the cancelButton is nil. So, the optional chain works correctly.
Please give me some time to fix it ☕️

**Comment by hsylife** [comment]
@tfsjohan  
I've update the brach "swift4".
Please try it out.
https://github.com/hsylife/SwiftyPickerPopover/tree/swift4

**Comment by tfsjohan** [comment]
Thank you! Will this branch work even if my own project and other pods are not yet updated to Swift 4?

**Comment by hsylife** [comment]
@tfsjohan 

How do you install SwiftyPickerPopover into your project? Via cocoapods?

By the way, I've just started to find the bugs on the brach for Swift3.

**Comment by hsylife** [comment]
@tfsjohan 

Yes, It will work. On each target setting, you can set up the Swift version on Xcode 9.

By the way, I've just started to find the bugs on the brach for Swift3.

**Comment by hsylife** [comment]
@tfsjohan 
I've fixed it both for Swift 3 and 4 for iOS 11.

Please `pod update`
