### ISSUE TITLE
Problem popover anchor at left top

### ISSUE THREAD

**Issue by kakame94** [hsylife/SwiftyPickerPopover#62]
Hi,
I'm swift beginner and I found this amazing library to do custom popover. Easily to implement, but as I said in the title how can I force the popover anchor to fix it "up" or on  the "down" side of my texfield or button.(I'm trying to doing a form).

![capture d ecran 2017-07-31 a 16 02 10](https://user-images.githubusercontent.com/10463715/28781229-a76d4128-7609-11e7-838e-5b2de21de138.png)
<img width="664" alt="capture d ecran 2017-07-31 a 16 02 51" src="https://user-images.githubusercontent.com/10463715/28781253-be81472e-7609-11e7-8440-a4723174a452.png">

Thanks in advances.

**Comment by hsylife** [comment]
Hello @kakame94 

> how can I force the popover anchor to fix it "up" or on the "down" side of my texfield or button.

If you'd like to fix it "up" on the textfield, you can specify them like this.

```
StringPickerPopover(title: "Mother", choices: ["Lili","Susie","Kattie"])
            .setPermittedArrowDirections(.up)
            .appear(originView: theTextfield, baseViewController: self)
```

I’d like you to close this issue when you have solved it ☕️

**Comment by kakame94** [comment]
Mr hsylife thank you !

**Comment by kakame94** [comment]
Same problem I'dont understand..
![capture d ecran 2017-07-31 a 21 25 01](https://user-images.githubusercontent.com/10463715/28794469-c69cc1e0-7636-11e7-9d2c-934a8445cd0c.png)
<img width="842" alt="capture d ecran 2017-07-31 a 21 26 57" src="https://user-images.githubusercontent.com/10463715/28794559-05a92b76-7637-11e7-9983-3fb51a1f9447.png">

**Comment by kakame94** [comment]
up!

**Comment by hsylife** [comment]
@kakame94 
What problem is "the same problem"? 
Did the same result as the first screenshot occurred?

By the way, only a single popover can be displayed at a time. The second and subsequent appear()s will be ignored.

**Comment by hsylife** [comment]
@kakame94 
Do you use the latest version of SwiftyPickerPopover?
If no, you need to `pod update` at first.

**Comment by kakame94** [comment]
Yes I know, only a single popover can be displayed at a time. But when I touch down the textfield my popover anchor is already fix at top left, for any button.
<img width="666" alt="capture d ecran 2017-08-01 a 15 43 06" src="https://user-images.githubusercontent.com/10463715/28828157-2bc8e712-76d0-11e7-9db0-43adb980727d.png">

**Comment by kakame94** [comment]
Solved Issue ! 
**Do you use the latest version of SwiftyPickerPopover?
If no, you need to pod update at first.**
Methods setDoneAction, and CancelAction are now setDoneButton and CancelButton.
But I don't understand why did you not let Cancel**Action** (setDone**Action**) ? Button means like everyone will use Button to show popover no ? (It's just UX thing I guess)

**Comment by hsylife** [comment]
@kakame94 
You've solved it. I'm glad to hear that. 

The reason why I've changed setDoneAction to setDoneButton is because I'd like to explain that this kind of functions set the properties related bar button item, including title.

And, could I close this issue?

**Comment by kakame94** [comment]
Yes
