### ISSUE TITLE
Swift 4 does not recognises NSAttributedStringKey.font

### ISSUE THREAD

**Issue by dipeshparashar** [hsylife/SwiftyPickerPopover#66]
Swift 4 does not recognises NSAttributedStringKey.font  in ColumnStringPickerPopover class.
You can see it here : https://imgur.com/a/WL6ZZ
If i let it fix the issue it gives further errors, as it converts .font to .zone which is not apt here.

**Comment by hsylife** [comment]
Thank you for your report!
Please give me some time to deal with it because I'm super busy ...

**Comment by hsylife** [comment]
@dipeshparashar 

Strange.
I confirmed that Xcode 9 (9A235) can recognize NSAttributedStringKey.font and built it.
I need to hear it more from you.
Is your Xcode version same to mine?

**Comment by dipeshparashar** [comment]
Yes : Version 9.0 (9A235), 
I am using NSAttributedStringKey.font in other projects as well. Xcode strangely reports only the new projects, not the old ones. 
For now, i have explicitly set the font attributes to nil for PickerPopover.

**Comment by hsylife** [comment]
OK. What is the Swift version? NSAttributedStringKey.font needs Swift4 compiler.

**Comment by eman6576** [comment]
This is also broken on Xcode 9.1

**Comment by eman6576** [comment]
@dipeshparashar @hsylife  Here is a fix that you can apply to the end of your Podfile if you are using CocoaPods:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'SwiftyPickerPopover'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            else
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```
This will force Xcode to use the Swift 4 toolchain when compling SwiftyPickerPopover.

**Comment by hsylife** [comment]
Thank you, @eman6576

I will replace the code with yours.

**Comment by jose920405** [comment]
Same issue here 6 months later in the version `(5.3.0)`
