### ISSUE TITLE
Segue on click

### ISSUE THREAD

**Issue by kwakueshun** [hsylife/SwiftyPickerPopover#67]
How to dismiss the view after clicking done? I need to do a segue but on clicking done, the view segues and then returns to previous page.

**Comment by hsylife** [comment]
Thank you for your question. I will reply to you later!

**Comment by hsylife** [comment]
@kwakueshun 
You can write it like this:
```
StringPickerPopover(title: "StringPicker", choices: ["value 1","value 2","value 3"])
  .setDoneButton(action: { [weak self] (popover, selectedRow, selectedString) in
      self?.navigationController?.popViewController(animated: true)
  })
  .appear(originView: button, baseViewController: self)
```

**Comment by kwakueshun** [comment]
@hsylife this still didn't do the trick for me. Could it be because I don't have my view controller embedded in a navigation controller? This is the code:
`StringPickerPopover(title: "Select A Rider", choices: ridernames)
                .setSelectedRow(0)
                .setDoneButton(action: { [weak self] (popover, selectedRow, selectedString) in    
                    self?.navigationController?.popViewController(animated: true)               
                    NotificationCenter.default.post(name: Constants.NOTIF_READY_TO_SEGUE, object: nil)               
                })
                .setCancelButton(action: { _, _, _ in
                    print("cancel")
                    self.locationManager.startUpdatingLocation()
                })
                .appear(originView: self.pickupLocationLabel, baseViewController: self)`

**Comment by kwakueshun** [comment]
@hsylife ok turns out I had to make the perform segue inside the closure after popping the controller. Thank you very much.

**Comment by hsylife** [comment]
Sure. The point is poping the controller in done closure.
