### ISSUE TITLE
[Swift 4] Cannot convert value of type

### ISSUE THREAD

**Issue by teofiluscandra** [hsylife/SwiftyPickerPopover#70]
Hi, i use Swift 4 branch and copy the example. 

`.setCancelButton(action: { v in
                print("cancel")
            })`

in cancel closure have error "_Cannot convert value of type '(_) -> ()' to expected argument type 'StringPickerPopover.ActionHandlerType?' (aka 'Optional<(StringPickerPopover, Int, String) -> ()>')_"

Thank you

**Comment by hsylife** [comment]
Sorry. It's a typo.

You can fix it as the following:
```
.setCancelButton(action: {_, _, _ in
                print("cancel") })
```

**Comment by teofiluscandra** [comment]
Okay, Thank you very much.
