### ISSUE TITLE
Not working for TextField

### ISSUE THREAD

**Issue by Neeraj204** [hsylife/SwiftyPickerPopover#73]
It is great library and thanks for your time.
As I have used this library over textfield, it makes Layout constraint different and the position of textfield and views are changing. Any help?

**Comment by hsylife** [comment]
Hi @Neeraj204,
I need to see your sample code for help.
Plus, I will add my sample code with text field as soon as possible!

**Comment by hsylife** [comment]
I've released the new sample code for UITextField.
First of all, please see it!

**Comment by hsylife** [comment]
Hello, @Neeraj204 
Have you solved the issue?
