### ISSUE TITLE
Customize Popover

### ISSUE THREAD

**Issue by Keibir** [hsylife/SwiftyPickerPopover#76]
Dear developers,

thanks a lot for your work!

Is it possible to change the edges to sharpe and not round ones?

**Comment by hsylife** [comment]
I've added new feature to master branch.
Now, setCornerRadius() is available.
If you want to change them to rectangle corners, you can write it like this.
```
let p = StringPickerPopover(title: "", choices: ["value 1","value 2","value 3"])
    .setCornerRadius(0)
    .appear(originView: sender, baseViewController: self)
```

**Comment by Keibir** [comment]
Thanks a lot!
