### ISSUE TITLE
Custom Fonts for DatePicker?

### ISSUE THREAD

**Issue by seenoevo** [hsylife/SwiftyPickerPopover#82]
Hello, is it possible to add custom fonts for the **Cancel** and **Done** buttons?

I see a parameter for `color` but no `font`?

Thanks!

**Comment by hsylife** [comment]
@seenoevo, I've implemented your idea into our master branch.
https://github.com/hsylife/SwiftyPickerPopover/pull/88

**Comment by seenoevo** [comment]
@hsylife works great...thanks for the flexibility in the parameters!
