### ISSUE TITLE
Crash when array in empty

### ISSUE THREAD

**Issue by jose920405** [hsylife/SwiftyPickerPopover#85]
When you pass an empty array inside `choices` cause the next crash

![captura de pantalla 2018-05-16 a la s 9 55 20 a m](https://user-images.githubusercontent.com/12536184/40124988-61382cc6-58ef-11e8-91be-df61b993592e.png)

**Comment by hsylife** [comment]
This is my bug. I will fix it by using `[safe: index]` extension asap.

**Comment by hsylife** [comment]
I've fixed the issue on the branch hotfix/issue-85 and will release it asap.

**Comment by hsylife** [comment]
@jose920405 OK. The fixed verision 6.2.1 has been available now. Please check it up!
