### ISSUE TITLE
A "clear" functionality for StringPickerPopover and ColumnStringPickerPopover

### ISSUE THREAD

**Issue by mspasov** [hsylife/SwiftyPickerPopover#89]
A small enhancement request from me - the ability clear the picked value when using StringPickerPopover or ColumnStringPickerPopover. Thanks.

**Comment by hsylife** [comment]
Thank you for your proposal. It sounds convenient.

**Comment by hsylife** [comment]
It has been available. Check the latest version, 6.5.0, which contains setClearButton(title:, font:, color:, action:) for String/ColumnStringPickerPopover.

**Comment by mspasov** [comment]
Hmm, it appears that it adds a blank selection on top. I was thinking more like dismissing the popover and executing the block (or just executing the block). Should be more consistent with the date* picking  mechanism (where clear just executes a block).

Also this means that handling cases (where clear should be visible or not) is more difficult to handle, because of the offset of the picked item changes. Tell me what do you think of that, i could make a quick PR if you want.
