### ISSUE TITLE
Crash in setSelectedRow line

### ISSUE THREAD

**Issue by jose920405** [hsylife/SwiftyPickerPopover#92]
![captura de pantalla 2018-05-24 a la s 3 58 27 p m](https://user-images.githubusercontent.com/12536184/40513441-6c2d1e52-5f6b-11e8-98b1-7b6e8d98cf42.png)

**Comment by hsylife** [comment]
What is your SwiftyPickerPopover version?

**Comment by jose920405** [comment]
(6.4.0) checked in `podfile.lock`.

I found that seems to be due to a change I made recently because i went back to a previous branch where this error did not occur.

I changed the way to navigate, using

`storyboard? .instantiateViewController`

and adding the `ViewController` using: `containerView.addSubview(vc!.view)`

Why this logic affect this module functionality?

**Comment by hsylife** [comment]
@jose920405 
You've updated to 6.4.0. It's OK.

I need to know more info. Which viewController is the popover written on?

**Comment by hsylife** [comment]
Your childViewController, which has the StringPickerPopover, is embedded on the parent vc via a containerView.

Do I understand your structure correctly?

**Comment by hsylife** [comment]
@jose920405 
I cannot reproduce your issue. Can you share the sample project, which reproduces it, with me?

**Comment by jose920405** [comment]
You sample project has exactly the same logic as mine

**Comment by jose920405** [comment]
I have been able to verify that the error is related to the path of the project.

![captura de pantalla 2018-05-28 a la s 9 40 30 a m](https://user-images.githubusercontent.com/12536184/40619696-a8deae36-625b-11e8-9a65-052f4e30d272.png)


Changing that name.. Works again.

**Comment by hsylife** [comment]
I'm happy to hear that you've solved the issue!
Thank you for the detail report!

**Comment by jose920405** [comment]
this error was something that was probably damaged in my directory?
Why did this module only affect?
