### ISSUE TITLE
dimmed background during Popover?

### ISSUE THREAD

**Issue by seenoevo** [hsylife/SwiftyPickerPopover#95]
Many thanks for this wonderful library!

Is it possible to allow users to control the alpha background color when a popover occurs, i.e. make the background color darker?

This gives the popover a more visual appearance of being a pop-up.

Similar to this popover:

![ezgif-1-9172aa2efe](https://user-images.githubusercontent.com/8109158/40594235-ccf27da8-61e2-11e8-84bc-a33d5f0c3fa7.gif)

Thanks!

**Comment by hsylife** [comment]
Thank you for your proposal: darker background appears behind the popover.
I will consider it.

**Comment by hsylife** [comment]
setDimmedBackgroundView(enabled:) has been introduced. Please check up the latest, (6.6.0).

**Comment by seenoevo** [comment]
Works great!
