### ISSUE TITLE
Tapping outside popover dismisses the baseViewController.

### ISSUE THREAD

**Issue by mspasov** [hsylife/SwiftyPickerPopover#98]
I think in the 0.6.6 refactoring a bug was introduced.

If the popover is dismissed by tapping outside it's view, when the disappear() method calls `baseViewController?.dismiss(animated: false, completion: completion)` the popover is already gone, and in case the baseViewController was presented modally, it will disappear as well.

edit: This happens when something in the baseViewController is the first responder.

**Comment by hsylife** [comment]
Thank you, @mspasov 
You are right.
I should change 'popover.disappear()' to 'dismiss(animated: false)' in tapped(button:) of each Popover.
I will fix it!

**Comment by hsylife** [comment]
I’ve released 6.6.1
